### ISSUE TITLE
way to inspect generated code?

### ISSUE THREAD

**Issue by JoshRagem** [fitzgen/libbindgen-tutorial-bzip2-sys#1]
is there one? I think it would be simpler for me to look at the rust definitions of the functions I want instead of reading the c header file.

**Comment by fitzgen** [comment]
There are a couple options:

* Read the bindings generated by `build.rs` in `./target/debug/build/libbindgen-tutorial-bzip2-sys-<blah>/out/bindings.rs`

* Run `cargo doc` to view the rustdocs for the crate.

Cheers!
